# Generated by Django 5.0 on 2023-12-26 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concessionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('numero_siret', models.IntegerField()),
                ('code_postal', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('chevaux', models.IntegerField()),
                ('concessionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.concessionnaire')),
            ],
        ),
    ]
